import Head from 'next/head';
//import styles from '@/styles/_Home.module.css';
import Link from "next/link";
import topics from "@/pages/api/topics";
import {Card, Container, Group, Text} from "@mantine/core";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Container>
                    <Group>
                        <Link href={'/hello'}>Hello</Link>
                        <Link href={'/about'}>About</Link>
                        <Link href={'/contacts'}>Contacts</Link>
                    </Group>
                    <Group align={'flex-start'}>
                        {topics.map((topic, index) => {
                            return <Link key={topic.id} style={{textDecoration: "none"}}
                                         href={`/learn/${topic.id}`}><Card shadow={'sm'} p={'lg'} radius={'md'} w={256}
                                                                           withBorder={true}><Card.Section>
                                <Text weight={500}>Learn {topic.id}</Text></Card.Section>
                            <Card.Section>
                                <Text size={'sm'} color={'dimmed'}>{topic.about}</Text>
                            </Card.Section>
                            </Card>
                            </Link>
                                ;
                        })}
                    </Group>
                </Container>
            </main>
        </>
    );
}
